[build]
  publish = "Builds"

[[headers]]
  for = "/Build/*.js.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Build/*.wasm.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Build/*.data.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Build/*.symbols.json.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/json"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Build/*.js.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Build/*.wasm.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Build/*.data.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/octet-stream"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Build/*.symbols.json.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/json"
    Cache-Control = "public, max-age=31536000, immutable"
